### ISSUE TITLE
Navigation issue - getting stuck in the blogs section

### ISSUE THREAD

**Issue by marsbard** [OrderOfTheBee/OrderOfTheBee.github.io#11]
From the home page, we click updates, now we see the blog, that's good, but from the user PoV the site hasn't changed, so they expect to click on the bee image at top left and for it to do what it did before, that is return to http://orderofthebee.org/

However 'updates' is hosted on 'http://posts.orderofthebee.org/' and so clicking the bee image goes there instead. 

The feeling is that there is no way to escape from the blog post page.

Please ensure that the bee image returns to the correct home. It may be necessary to have a 'blog posts home' link on the posts.ootb subdomain.

**Comment by aviriel** [comment]
The idea was that people can return from any page of the blog to the blog index page. I understand that it's correct behaviour when logo points to http://orderofthebee.org. But as for me, then it is really comfortably when in the blog it points to http://blog.orderofthebee.org. Any other link in the top navbar (except UPDATES) returns user to the website.

**Comment by marsbard** [comment]
It doesn't really make sense for the behaviour of that UI element to change when the context changes from github to tumblr, from the user's point of view there is no context change

**Comment by aviriel** [comment]
Fixed
