### ISSUE TITLE
First click of 'Sponsors' gets hidden

### ISSUE THREAD

**Issue by marsbard** [OrderOfTheBee/OrderOfTheBee.github.io#14]
First click of 'Sponsors' firstly shows the sponsors but then when the members list is loaded the sponsors part of the page disappears, actually it has just moved down the page as the images are loaded and their sizes are known by the renderer. Once you have already visited the 'about' page this is not an issue as the images have loaded but you can get to sponsors from the submenu of "about us" which means the images may not have already been loaded

The only two ways I can think of around this would be either to put the members list beneath the sponsors, or else to include the vertical size of the images in the image tags, so that the image can be rendered at the right height before the image is actually loaded. It would also be possible to track the position of the sponsors heading with javascript and scroll to it if it moves, but this feels less satisfactory.

**Comment by aviriel** [comment]
I added "height" attribute for all images, I hope it will help.
