### ISSUE TITLE
Web site is not listing Members

### ISSUE THREAD

**Issue by esplinr** [OrderOfTheBee/OrderOfTheBee.github.io#18]
The members list is not showing when I browse to this URL:
http://orderofthebee.org/about/#members

I checked both Firefox and Chrome. The errors are confusing because they come from the Angular code, but the problem appears to be an "Unexpected Token" in http://orderofthebee.org/assets/data/members.json

I suspect the change is related to @aviriel's commit two days ago, but I don't see anything obviously wrong with the commit.

**Comment by AFaust** [comment]
It is related to a descriptive text where a single quote is used for a contraction of "I" and "am".

**Comment by AFaust** [comment]
Turns out there was a special whitespace character in that line that only showed up as a normal whitespace in the editor. It has been removed and members now load correctly again.

**Comment by esplinr** [comment]
Thanks @AFaust!
